[tox]
env_list = 3.14, 3.13, 3.12, 3.11, 3.10

[testenv]
description = run the test suite with pytest
deps =
  flake8>=7.3.0,<8.0.0
  anyio==4.13.0
  pytest==9.0.3
  pytest-cov==7.1.0
  pytest-timeout==2.4.0
  pytest-xdist==3.8.0
  tomlkit==0.15.0
labels = test
commands = pytest
